# Generated by Django 4.0.2 on 2022-03-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_options_alter_clipping_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
